export const DOC_CATEGORY = [
    { value: 'personal', label: 'Personal Documents ' },
    { value: 'housing', label: 'Housing Information' },
    { value: 'utility', label: 'Utility Information' },
    { value: 'misc', label: 'Miscellaneous' },
    { value: 'absent', label: 'Absent Parent/LRR' },
    { value: 'income', label: 'Income/Financial Statement ' },
    { value: 'correspondence', label: 'Correspondence/Notices' },
    { value: 'agency', label: 'Inter/Intra Agency Correspondence' },
    { value: 'match', label: 'Match Information' },
    { value: 'unscannable', label: 'Unscannable  Documents' },
    { value: 'employment', label: 'Employment Documents' },
    { value: 'food', label: 'Food Stamps' },
    { value: 'medicaid', label: 'Medicaid' },
    { value: 'rau', label: 'RAU' },
    { value: 'bev', label: 'BEV' },
    { value: 'homebound', label: 'Home Visit/Homebound Documentation' },
    { value: 'disaster', label: 'Disaster SNAP' },
    { value: 'internal', label: 'Internal Paper Authorization Document' },
    { value: 'child-care', label: 'Child Care CILOCA' },
    { value: 'fair', label: 'Fair Fares' },
]