export const LANGUAGE_OPTIONS = [
    { value: 'african-languages', label: 'African Languages' },
    { value: 'albanian', label: 'Albanian' },
    { value: 'arabic', label: 'Arabic' },
    { value: 'chinese-cantonese', label: 'Chinese-Cantonese' },
    { value: 'chinese-mandarin', label: 'Chinese-Mandarin' },
    { value: 'chinese-other', label: 'Chinese-Other' },
    { value: 'chinese-traditional', label: 'Chinese Traditional' },
    { value: 'chinese-simplified', label: 'Chinese Simplified' },
    { value: 'english', label: 'English' },
    { value: 'farsi', label: 'Farsi' },
    { value: 'french', label: 'French' },
    { value: 'french-creole', label: 'French Creole' },
    { value: 'german', label: 'German' },
    { value: 'greek', label: 'Greek' },
    { value: 'hebrew', label: 'Hebrew' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'italian', label: 'Italian' },
    { value: 'japanese', label: 'Japanese' },
    { value: 'khmer', label: 'Khmer' },
    { value: 'korean', label: 'Korean' },
    { value: 'laotian-lao', label: 'Laotian/Lao' },
    { value: 'native-american', label: 'Native American' },
    { value: 'polish', label: 'Polish' },
    { value: 'portuguese', label: 'Portuguese' },
    { value: 'russian', label: 'Russian' },
    { value: 'serbo-croation', label: 'Serbo-Croation' },
    { value: 'sign-language', label: 'Sign Language' },
    { value: 'spanish', label: 'Spanish' },
    { value: 'swedish', label: 'Swedish' },
    { value: 'tagalog', label: 'Tagalog' },
    { value: 'thai', label: 'Thai' },
    { value: 'urdu', label: 'Urdu' },
    { value: 'vietnamese', label: 'Vietnamese' },
    { value: 'yiddish', label: 'Yiddish' },
    { value: 'alaskan', label: 'Alaskan' },
    { value: 'am-ind-apache', label: 'AM IND - Apache' },
    { value: 'am-ind-crow', label: 'AM IND - Crow' },
    { value: 'am-ind-dakota', label: 'AM IND - Dakota' },
    { value: 'am-ind-choctaw', label: 'AM IND - Choctaw' },
    { value: 'am-ind-lakota', label: 'AM IND - Lakota' },
    { value: 'am-ind-nakota', label: 'AM IND - Nakota' },
    { value: 'am-ind-navajo', label: 'AM IND - Navajo' },
    { value: 'am-ind-other', label: 'AM IND - Other' },
    { value: 'am-ind-zuni', label: 'AM IND - Zuni' },
    { value: 'amharic', label: 'Amharic' },
    { value: 'armenian', label: 'Armenian' },
    { value: 'assyrian', label: 'Assyrian' },
    { value: 'bengali', label: 'Bengali' },
    { value: 'bosnian', label: 'Bosnian' },
    { value: 'braille', label: 'Braille' },
    { value: 'bulgarian', label: 'Bulgarian' },
    { value: 'burmese', label: 'Burmese' },
    { value: 'cambodian', label: 'Cambodian' },
    { value: 'chinese-fujian', label: 'Chinese - Fujian' },
    { value: 'chamorro', label: 'Chamorro' },
    { value: 'chin-toisanese', label: 'Chin - Toisanese' },
    { value: 'creole-criollo', label: 'Creole - Criollo' },
    { value: 'creole-haitian', label: 'Creole - Haitian' },
    { value: 'creole-other', label: 'Creole - Other' },
    { value: 'croatian', label: 'Croatian' },
    { value: 'czech', label: 'Czech' },
    { value: 'dutch', label: 'Dutch' },
    { value: 'dzongkha', label: 'Dzongkha' },
    { value: 'finnish', label: 'Finnish' },
    { value: 'gujarati', label: 'Gujarati' },
    { value: 'hmong', label: 'Hmong' },
    { value: 'hungarian', label: 'Hungarian' },
    { value: 'ilocano', label: 'Ilocano' },
    { value: 'indonesian', label: 'Indonesian' },
    { value: 'karen', label: 'Karen' },
    { value: 'kinyarwanda', label: 'Kinyarwanda' },
    { value: 'kirundi-rundi', label: 'Kirundi (Rundi)' },
    { value: 'kizigna', label: 'Kizigna' },
    { value: 'kurdish', label: 'Kurdish' },
    { value: 'lithuanian', label: 'Lithuanian' },
    { value: 'maay', label: 'Maay' },
    { value: 'macedonian', label: 'Macedonian' },
    { value: 'malayalam', label: 'Malayalam' },
    { value: 'mongolian', label: 'Mongolian' },
    { value: 'nepali', label: 'Nepali' },
    { value: 'norwegian', label: 'Norwegian' },
    { value: 'oneida', label: 'Oneida' },
    { value: 'onondaga', label: 'Onondaga' },
    { value: 'oromo', label: 'Oromo' },
    { value: 'pashto', label: 'Pashto' },
    { value: 'pennsylvania-dutch', label: 'Pennsylvania Dutch' },
    { value: 'persian', label: 'Persian' },
    { value: 'pidgin-hawaiian', label: 'Pidgin - Hawaiian' },
    { value: 'punjabi', label: 'Punjabi' },
    { value: 'romanian', label: 'Romanian' },
    { value: 'samoan', label: 'Samoan' },
    { value: 'seneca', label: 'Seneca' },
    { value: 'serbian', label: 'Serbian' },
    { value: 'shinnecock', label: 'Shinnecock' },
    { value: 'slovak', label: 'Slovak' },
    { value: 'somali', label: 'Somali' },
    { value: 'mohawk', label: 'Mohawk' },
    { value: 'swahili', label: 'Swahili' },
    { value: 'syriac', label: 'Syriac' },
    { value: 'tigrinya', label: 'Tigrinya' },
    { value: 'tona-seneca', label: 'Tona - Seneca' },
    { value: 'tongan', label: 'Tongan' },
    { value: 'turkish', label: 'Turkish' },
    { value: 'tuscarora', label: 'Tuscarora' },
    { value: 'twi-fanti', label: 'Twi (Fanti)' },
    { value: 'ukrainian', label: 'Ukrainian' },
    { value: 'unkechauga', label: 'Unkechauga' },
    { value: 'yugoslavian', label: 'Yugoslavian' },
]