export const RELATIONSHIP = [
    { value: 'applicant', label: 'Applicant/Payee' },
    { value: 'legal-spouse', label: 'Legal Spouse' },
    { value: 'nlu-child-uncommon', label: 'Non-Legal Union (No Child in Common)' },
    { value: 'son', label: 'Son' },
    { value: 'daughter', label: 'Daughter' },
    { value: 'step-son', label: 'Step-Son' },
    { value: 'step-daughter', label: 'Step-Daughter' },
    { value: 'niece-nephew', label: 'Niece or Nephew' },
    { value: 'grandson-granddaughter', label: 'Grandson or Granddaughter' },
    { value: 'grandmother-grandfather', label: 'Grandmother or Grandfather' },
    { value: 'aunt-uncle', label: 'Aunt or Uncle' },
    { value: 'essential-person', label: 'Essential Person' },
    { value: 'fa-snfp', label: 'Other FA/SNFP Relationship' },
    { value: 'not-fa-snfp', label: 'Other Relationship (Not FA/SNFP Relationship)' },
    { value: 'legal-guardian', label: 'Legal Guardian (Not FA/SNFP Relationship)' },
    { value: 'ward', label: 'Ward (Not ADC Eligible Relationship)' },
    { value: 'cousin', label: 'Cousin' },
    { value: 'none', label: 'None' },
    { value: 'parent', label: 'Parent' },
    { value: 'sister-brother', label: 'Sister or Brother' },
    { value: 'step-parent', label: 'Step-Parent' },
    { value: 'step-sister-brother', label: 'Step-Sister or Step-Brother' },
    { value: 'half-sibling', label: 'Half Sibling' },
    { value: 'putative-father', label: 'Putative Father' },
    { value: 'acknowledging-father', label: 'Acknowledging Father' },
    { value: 'great-grandparent', label: 'Great Grandparent' },
    { value: 'great-grandchild', label: 'Great Grandchild' },
    { value: 'alternate-payee', label: 'Alternate Payee' },
    { value: 'unknown-system-generated', label: 'Unknown (System Generated Only)' },
    { value: 'nlu-child-common', label: 'Non-Legal Union with Child in Common' },
    { value: 'unknown', label: 'Unknown' },
    { value: 'unborn', label: 'Unborn' },
]