export const SHELTER_TYPES = [
    { value: 'rent', label: 'Rent' },
    { value: 'rent-public', label: 'Rent Public' },
    { value: 'own-home', label: 'Own Home' },
    { value: 'room-and-board', label: 'Room and Board' },
    { value: 'hotel-permanent', label: 'Hotel Permanent' },
    { value: 'hotel-temporary', label: 'Hotel Temporary' },
    { value: 'migrant-camp', label: 'Migrant Camp' },
    { value: 'medical-facility', label: 'Medical Facility' },
    { value: 'room-only', label: 'Room Only' },
    { value: 'alcohol-treatment', label: 'Alcohol Treatment Facility (non-Level II)' },
    { value: 'public-home', label: 'Public Home' },
    { value: 'cc1-nyc', label: 'Level I Congregate Care (NYC, Nassau, Suffolk and Westchester)' },
    { value: 'cc2-nyc', label: 'Level II Congregate Care (NYC, Nassau, Suffolk and Westchester)' },
    { value: 'foster-care', label: 'Foster Care' },
    { value: 'emergency-assistance', label: 'Emergency Assistance Rehousing Program' },
    { value: 'domestic-violence', label: 'Shelter for Victim of Domestic Violence' },
    { value: 'undomiciled', label: 'Undomiciled' },
    { value: 'cc1-upstate', label: 'Congregate Care Level I (Upstate)' },
    { value: 'cc2-upstate', label: 'Congregate Care Level II (Upstate)' },
    { value: 'homeless1', label: 'Homeless Shelter - Tier II - less than 3 meals per day' },
    { value: 'homeless2', label: 'Homeless Shelter - Tier II - 3 meals per day' },
    { value: 'homeless3', label: 'Homeless Shelter - Non Tier I or Tier II' },
    { value: 'homeless4', label: 'Shelter for Homeless - less than 3 meals per day' },
    { value: 'residential-program', label: 'Residential Program for Victims of Domestic Violence - less than 3 meals per day' },
    { value: 'cc3-nyc', label: 'Congregate Care Level III - Enhanced Residential care(NYC, Nassau, Suffolk, Westchester and Rockland)' },
    { value: 'specialized-housing', label: 'Supportive Specialized Housing' },
    { value: 'cc3-upstate', label: 'Congregate Care Level III - Enhanced Residential care (Rest of the State)' }
]