export const INSURANCE_INFORMATION_STATUS = {
    healthInsurance: {
        medicaid: 1 << 0,
        medicaidCardId: 1 << 1,
        familyHealthPlus: 1 << 2,
        familyHealthPlusCardId: 1 << 3,
        commercialInsurance: 1 << 4,
        personsCovered: 1 << 5,
        costOfPolicy: 1 << 6,
        endDateOfCoverage: 1 << 7,
        medicare: 1 << 8,
        medicalAssistance: 1 << 9,
        jobHealthInsurance: 1 << 10,
    },
    medicalExpense: {
        recentMedicalBill: 1 << 0,
        monthBilled: 1 << 1,
        oldMedicalBill: 1 << 2,
        pendingLawsuit: 1 << 3,
        injured: 1 << 4,
        recentMoveIn: 1 << 5,
        moveInState: 1 << 6,
        moveInCounty: 1 << 7,
    },
    deceasedOrLivingOutside: {
        parentDeceased: 1 << 0,
        parentLivingOutside: 1 << 1,
        parentPrivacy: 1 << 2,
        parentName: 1 << 3,
        parentDob: 1 << 4,
        parentStreet: 1 << 5,
        parentCity: 1 << 6,
        parentSsn: 1 << 7,
        spouseDeceased: 1 << 8,
        spouseLivingOutside: 1 << 9,
        spousePrivacy: 1 << 10,
        spouseName: 1 << 11,
        spouseDob: 1 << 12,
        spouseStreet: 1 << 13,
        spouseCity: 1 << 14,
        spouseSsn: 1 << 15,
    },
    healthPlan: {
        healthPlan: 1 << 0,
        healthPlanName: 1 << 1,
        currentDoctor: 1 << 2,
        preferredDoctor: 1 << 3,
        obGyn: 1 << 4,
    }
}